# Generated by Django 4.2.7 on 2024-02-06 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetoken',
            name='query_id',
        ),
        migrations.RemoveField(
            model_name='devicetokenblacklist',
            name='query_id',
        ),
        migrations.RemoveField(
            model_name='devicewallet',
            name='query_id',
        ),
        migrations.AlterField(
            model_name='device',
            name='login_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.deviceloginhistory'),
        ),
        migrations.AlterField(
            model_name='device',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.devicewallet'),
        ),
    ]
