# Generated by Django 4.2.7 on 2024-02-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_emailverificationotp_query_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='query_id',
        ),
    ]
