# Generated by Django 4.2.7 on 2024-02-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_device_query_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
