# Generated by Django 4.2.7 on 2024-02-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_device_device_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceloginhistory',
            name='logout_at',
            field=models.DateTimeField(null=True),
        ),
    ]
