# Generated by Django 4.2.7 on 2024-02-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_query_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='query_id',
            field=models.BinaryField(db_index=True, max_length=10000),
        ),
    ]
