# Generated by Django 4.2.7 on 2024-02-10 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0009_group_remove_userprofile_status_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='group',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='base_group',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.group'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('_type', 'base_group')},
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_ptr',
        ),
    ]
