# Generated by Django 4.2.7 on 2024-02-17 14:01

import accounts.models.profiles
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_group_managers_group_base_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='statuses',
            field=models.JSONField(default=accounts.models.profiles.UserProfile.default_statuses),
        ),
    ]
